apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - image: frijugsincek/images:2021-01-02-20-01-14
          name: images
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://suleiman.db.elephantsql.com:5432/trchrzvw
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: trchrzvw
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: images-pass
                  key: KUMULUZEE_DATASOURCES0_IMAGES_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP


---


#apiVersion: v1
#kind: Service
#metadata:
#  name: images
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 8080
#      protocol: TCP
#      targetPort: server
#  selector:
#    app: images

apiVersion: v1
kind: Service
metadata:
  name: images
spec:
  selector:
    app: images
  ports:
    - name: web
      port: 8080
  type: ClusterIP