kumuluzee:
  name: images-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImagesDS
      connection-url: jdbc:postgresql://localhost:5432/images
      username: dbimage
      password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImagesDS
  metrics:
    web-instrumentation:
      - name: images-endpoint
        url-pattern: /v1/images/*
  config:
    consul:
#      agent: http://40.88.21.225:80
      agent: http://localhost:4200
  cors-filter:
    servlet:
      allow-origin: "http://localhost:4200"
      allow-subdomains: true
      supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"
app-properties:
  recognition-key:
  use-apis: false